// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnU_s8oDaNI34S_Br9h5EEupaFyC3MxgA',
    appId: '1:1072398312956:web:c6a257d646a5b68bd53e79',
    messagingSenderId: '1072398312956',
    projectId: 'proyecto2-17401014',
    authDomain: 'proyecto2-17401014.firebaseapp.com',
    storageBucket: 'proyecto2-17401014.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC88CeTowifeJgRJYqxorIykLtSuqOhn9c',
    appId: '1:1072398312956:android:fc355833ca13090fd53e79',
    messagingSenderId: '1072398312956',
    projectId: 'proyecto2-17401014',
    storageBucket: 'proyecto2-17401014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzLcHk0qk1rbN7uI-UdCzoAQ6GwC2G_yI',
    appId: '1:1072398312956:ios:fbf1773a61c748a9d53e79',
    messagingSenderId: '1072398312956',
    projectId: 'proyecto2-17401014',
    storageBucket: 'proyecto2-17401014.appspot.com',
    iosClientId: '1072398312956-htl6160ddjh8uep3mj8l0te5gaqqftbb.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto217401014',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzLcHk0qk1rbN7uI-UdCzoAQ6GwC2G_yI',
    appId: '1:1072398312956:ios:fbf1773a61c748a9d53e79',
    messagingSenderId: '1072398312956',
    projectId: 'proyecto2-17401014',
    storageBucket: 'proyecto2-17401014.appspot.com',
    iosClientId: '1072398312956-htl6160ddjh8uep3mj8l0te5gaqqftbb.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto217401014',
  );
}
